version: '3'

services:
  ################################
  #   setup web container for prod
  ################################
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - 80:5000
