CREATE TABLE IF NOT EXISTS Users
(

    id UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    username VARCHAR (127) NOT NULL UNIQUE,
    email VARCHAR (127) NOT NULL UNIQUE,
    password VARCHAR (127) NOT NULL,
    PRIMARY KEY (id)
)